### ISSUE TITLE
Allow deep merging with `db.patch`

### ISSUE THREAD

**Issue by conorshaw** [get-convex/convex-js#12]
Hey 👋, I would like to use convex for an app I am building, however I would require `db.patch` to allow for deep merging into documents. I see this used to be the default case but was changed last year. Is it on the cards to allow this behaviour?

Thanks!

Reference: https://news.convex.dev/announcing-convex-0-16-0/#:~:text=Breaking%3Adb.patch%20performs%20shallow%20merge

**Comment by thomasballinger** [comment]
We changed this because it was confusing to reason about. If you need a deep patch, get the object and spread in the change manually; today this is no different for bandwidth and speed.

In the future when we have the ability to fetch only portions of an object, yes this could be in the cards. Since there's no benefit today vs. doing the more explicit thing this isn't planned right now.
